project:
  type: website
  output-dir: docs

website:
  title: "Quantum of Science"
  site-url: "https://weckmantimo.github.io/weckman-blog/"
  open-graph: true
  twitter-card: true
  navbar:
    left:
      - text: Home
        file: index.qmd
      - text: Publications
        file: publications.qmd
      - text: Blog posts
        file: blog_index.qmd
    right:
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=JLvgAfYAAAAJ
      - icon: linkedin
        href: https://linkedin.com/in/timo-weckman-829327123/
      - text: "ORCID"
        href: https://orcid.org/0000-0001-8721-560X
      - icon: github
        href: https://github.com/WeckmanTimo
format:
  html:
    theme: cosmo
    css: styles.css
    include-in-header: _includes/meta.html
    include-before-body: _includes/header.html
    include-after-body: _includes/footer.html
